function styleAxes(ax, tokens)
%STYLEAXES Apply the suite-wide axes style for the given theme.
%   Every plot in Dynamics Lab goes through this, so all simulators share
%   one look and switch themes together.
arguments
    ax (1,1)
    tokens (1,1) dlab.ui.Theme
end
set(ax, ...
    Color=tokens.AxesBackground, ...
    XColor=tokens.AxesForeground, ...
    YColor=tokens.AxesForeground, ...
    ZColor=tokens.AxesForeground, ...
    GridColor=tokens.Grid, ...
    GridAlpha=0.55, ...
    MinorGridColor=tokens.Grid, ...
    ColorOrder=tokens.Series, ...
    FontSize=tokens.FontSize.sm + 1, ...
    Box="on", ...
    XGrid="on", YGrid="on", ZGrid="on");
ax.Title.Color = tokens.Text;
ax.Title.FontWeight = "bold";
if isprop(ax, "BackgroundColor")
    ax.BackgroundColor = tokens.AxesBackground;   % uiaxes surround
end
end
